### ISSUE TITLE
Local Links

### ISSUE THREAD

**Issue by mlin25** [sonnenkern/quip-export#2]
I am so excited to find this amazing tool for quip export! Just one suggestion: is it possible to replace the links to other files with the local path, instead of a quip web link?

**Comment by sonnenkern** [comment]
Hi, thank you a lot for the suggestion and nice words about my tool. How I understood, you are speaking about the references to other Quip documents or folders in the same Quip account. 

I've added the new CLI option "**--resolve-references**", which solve the problem with this kind of references. All cross-document references are resolved to the relative paths. Please note, that this kind of relative paths won't work if you move the file somewhere else or separate it from original folder structure. 

All the changes available in version 1.9.0 (command line tool, npm-module). The new feature is NOT available in online web-version (www.quip-export.com). 

Are you using web-version either? Could you try the export tool, if it solves your problem? Please let me know about the result.

**Comment by mlin25** [comment]
Sorry for my late reply. I just tested your new feature and greatly appreciated! "--resolve-reference" works well for some links but some failed. For the others which still link to a quip webpage, I think the similarity is that they are all under a deeper sub-folder: not working from the 3rd layer sub-folders. Is it possible to revise this issue? Thanks.

**Comment by sonnenkern** [comment]
Hi, thank you for the contribution. It's very strange, because I've tested all possible cross-references with my demo account with deepness level 6 for folders and files. Everything works for me... But I will try to find, why it doesn't work for you. I've just published new version 1.9.2. I've injected some debug outputs. Could you try it again, but with options "--resolve-references" and "--debug". Last option will generate some outputs in the log-file (export.log). Could you send me please this file on info@quip-export.com. I will analyze the logs and will try to find out what is going wrong. Don't worry, in the log-file you will not found any private or secure data - that is just normal text file, that you can read it in any text editor. All the links listed there are accessible only after your log in in your Quip account. It means, nobody could access your data over the links from log. Cold you also give me some links from your Quip export files, that don't work. I need to know how they are built. If you want, we could use private emails for our conversation. It is not really necessary to publish everything hier on GitHub.

**Comment by mlin25** [comment]
I guess I know what's the problem! Those "don't work" links are in the "Calendar". I think you can try to insert a calendar in your test document, and add some Quip links inside that Calendar. 

The log-file only output some counts of the folders and threads. I think they might not help? And after your test, if it is not the "links in calendar issue", I am happy to have private discussions with you about the links sharing.

**Comment by mlin25** [comment]
Hi,

I tried version 1.9.6 and every link connects to a quip webpage. Maybe you forgot some minor revise? Thanks.

**Comment by sonnenkern** [comment]
Hi, could you try the new version 1.10.0. Thnx.
